kind: ConfigMap 
apiVersion: v1 
metadata:
  name: example-configmap 
data:
  testFloat: 1.11
  nameOfAnotherConfigMap: null
  nameOfSecret: null
  nameOfStorageClass: null
  nameOfIngressClass: null
  listOfStrings:
    - string1
    - string2
  yamlFile: null
  tmplFile: null
  cloudCredential: null
  docker:
    enabled: false
    path: ''